#!/bin/bash
# There were some pages that didn't resolve due to latency so I had to filter and redownload.
# Turned out a lot of them just didnt have any videos but the pattern still gave a result because it still links to that ip

echo "" > .oldlist
while read entry; do 
	ls -l  $entry.txt >> .oldlist
done < .newlist
#ls *.txt -l > .oldlist
echo "[*] Listed"
echo "" > .newlist
while read entry; do
	if [ $(echo $entry | cut -c32- | sed -e "s/S.*//g") -eq "150"  ]; then
		var=$(echo $entry | sed -e "s/.*:[0-9][0-9] //g" -e "s/\.txt//g")
		echo $var  >> .newlist
		echo $var
	fi
done < .oldlist
